In [1]:
import numpy as np

In [3]:
a = np.arange(12,24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [12]:
a1 = a.reshape(1,12)
a2 = a.reshape(2,6)
a3 = a.reshape(3,4)
a4 = a.reshape(4,3)
a5 = a.reshape(6,2)


print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17 18 19 20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [14]:
b1 = a.reshape(-1,12)
b2 = a.reshape(-1,6)
b3 = a.reshape(3,-1)
b4 = a.reshape(4,-1)
b5 = a.reshape(6,-1)

print(b1)
print(b2)
print(b3)
print(b4)
print(b5)

[[12 13 14 15 16 17 18 19 20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [ ]:
#Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
#Ответ - нет, для обращения к элементу массива понадобится указывать два индекса.

In [32]:
import random

mu = 0
sigma = 0.1
N = 3
M = 4

nums =np.array([[random.normalvariate(mu, sigma) for j in range(M)] for i in range(N)])
print(nums)

print(nums.size)

rd = np.asarray(nums).ravel()
print(rd)
print(rd.size)

[[-0.1148932  -0.05673488 -0.07611844  0.04896995]
 [ 0.15421296 -0.00394898  0.11521377  0.12339812]
 [ 0.01069764 -0.16668048  0.1068586  -0.02510144]]
12
[-0.1148932  -0.05673488 -0.07611844  0.04896995  0.15421296 -0.00394898
  0.11521377  0.12339812  0.01069764 -0.16668048  0.1068586  -0.02510144]
12


In [34]:
#Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
a = np.arange(20,0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [48]:
#Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
#В чем разница между массивами a и b?
#
b = np.arange(20,1, -2).reshape(1,-1)

print(b)


[[20 18 16 14 12 10  8  6  4  2]]


In [53]:
N = 2
M = 2

a = np.array([[0 for j in range(M)] for i in range(N)])
b = np.array([[1 for j in range(M)] for i in range(N + 1)])

print(a)
print(b)

d = np.vstack([a,b])

print(d)
print(d.size)

[[0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]
[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]
10


In [69]:
from numpy import linalg as LA

a = np.arange(0,12)
A = a.reshape(4,3)
print(f"Вектор а:\n{a}")
print(f"Матрица A:\n{A}")

At = A.T

print(f"Матрица At:\n{At}")

B = A.dot(At)
print(f"Матрица B:\n{B}")

Bdet = LA.det(B)
if(Bdet == 0):
    print(f"Обратная матрица к B не существует, так как матрица B сингулярная")
else:
    Binv = LA.inv(B)
    print(Binv)

Вектор а:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Матрица A:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Матрица At:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
Матрица B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Обратная матрица к B не существует, так как матрица B сингулярная


In [72]:
random.seed(42)
from random import randint

In [81]:
m = np.array([randint(0, 16) for j in range(16)])
C = m.reshape(4,-1)
print(f"Матрица m:\n{m}")
print(f"Матрица C:\n{C}")

Матрица m:
[10 15  0  3 11  9  7  1  7  2  2 15  2  4  4 15]
Матрица C:
[[10 15  0  3]
 [11  9  7  1]
 [ 7  2  2 15]
 [ 2  4  4 15]]


In [84]:
D = B + 10*C
Ddet = LA.det(D)
Drange = np.ptp(D)
Dinv = LA.inv(D)

print(f"Определитель = {Ddet}, Ранг = {Drange}. Матрица D:\n{D}\n Матрица Dinv:\n{Dinv}")

Определитель = 490445199.9999993, Ранг = 429. Матрица D:
[[105 164  23  62]
 [124 140 156 132]
 [ 93 106 169 362]
 [ 52 162 252 452]]
 Матрица Dinv:
[[-0.00100064  0.00454191  0.01175577 -0.01060416]
 [ 0.00719183 -0.00241307 -0.00859268  0.00659996]
 [-0.00676797  0.00885171 -0.00585794  0.00303488]
 [ 0.00131081 -0.00459268  0.00499318 -0.00062515]]


In [85]:
Dinv = np.where(Dinv < 0, 0, 1)
print(f"Матрица Dinv:\n{Dinv}")

Матрица Dinv:
[[0 1 1 0]
 [1 0 0 1]
 [0 1 0 1]
 [1 0 1 0]]


In [86]:
E = np.where(Dinv == 1, B, C)
print(f"Матрица E:\n{E}")
print(f"Матрица B:\n{B}")
print(f"Матрица C:\n{C}")

Матрица E:
[[ 10  14  23   3]
 [ 14   9   7 122]
 [  7  86   2 212]
 [ 32   4 212  15]]
Матрица B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Матрица C:
[[10 15  0  3]
 [11  9  7  1]
 [ 7  2  2 15]
 [ 2  4  4 15]]
