In [3]:
import numpy as np

In [15]:
ar = np.array([1, 6, 2,  8, 3, 11 , 3,   10, 1, 7])
a = ar.reshape(5, 2)

print(a)

mean_a = a.mean(axis=0)

print(mean_a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
[2.  8.4]


In [18]:
a_centered = a - mean_a

print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [21]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])

N = a_centered.shape[0]

a_centered_sp = a_centered_sp / (N - 1)

print(a_centered_sp)


2.0


In [22]:
a_tr = np.transpose(a)

a_cov = np.cov(a_tr)

print(a_tr)

print(a_cov)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
[[1.  2. ]
 [2.  4.3]]
